name: sneakears_shop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  linter: ^1.20.0
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  google_fonts: ^2.3.1
  sizer: ^2.0.15
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/cart.png
  